// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: identity/data/service.proto

package dataconnect

import (
	data "buf.build/gen/go/authaas/identity-data/protocolbuffers/go/identity/data"
	connect "connectrpc.com/connect/v2"
	context "context"
	sync "sync"
)

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "identity.data.Service"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceGetProcedure is the procedure name of the Service's Get RPC.
	ServiceGetProcedure = "/identity.data.Service/Get"
	// ServiceDeleteProcedure is the procedure name of the Service's Delete RPC.
	ServiceDeleteProcedure = "/identity.data.Service/Delete"
	// ServiceGetGrantHashProcedure is the procedure name of the Service's GetGrantHash RPC.
	ServiceGetGrantHashProcedure = "/identity.data.Service/GetGrantHash"
	// ServiceClearGrantProcedure is the procedure name of the Service's ClearGrant RPC.
	ServiceClearGrantProcedure = "/identity.data.Service/ClearGrant"
)

var (
	serviceGetSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     data.File_identity_data_service_proto.Services().ByName("Service").Methods().ByName("Get"),
			Procedure:  ServiceGetProcedure,
		}
	})
	serviceDeleteSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     data.File_identity_data_service_proto.Services().ByName("Service").Methods().ByName("Delete"),
			Procedure:  ServiceDeleteProcedure,
		}
	})
	serviceGetGrantHashSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     data.File_identity_data_service_proto.Services().ByName("Service").Methods().ByName("GetGrantHash"),
			Procedure:  ServiceGetGrantHashProcedure,
		}
	})
	serviceClearGrantSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     data.File_identity_data_service_proto.Services().ByName("Service").Methods().ByName("ClearGrant"),
			Procedure:  ServiceClearGrantProcedure,
		}
	})
)

// ServiceClient is a client for the identity.data.Service service.
type ServiceClient interface {
	// The identity's record. Refuses an unknown principal.
	Get(context.Context, *data.GetRequest) (*data.GetResponse, error)
	// Removes the identity. Refuses an unknown principal.
	Delete(context.Context, *data.DeleteRequest) (*data.DeleteResponse, error)
	// The digest of the identity's outstanding grant; unset when none is
	// outstanding. Refuses an unknown principal.
	GetGrantHash(context.Context, *data.GetGrantHashRequest) (*data.GetGrantHashResponse, error)
	// Clears the outstanding grant while its digest still equals the one
	// presented. Refuses when it does not, and clears nothing.
	ClearGrant(context.Context, *data.ClearGrantRequest) (*data.ClearGrantResponse, error)
}

// NewServiceClient constructs a client for the identity.data.Service service. Multiple service
// clients may share a single connect.Client.
func NewServiceClient(client *connect.Client) ServiceClient {
	return &serviceClient{client: client}
}

// ServiceHandler is an implementation of the identity.data.Service service.
type ServiceHandler interface {
	// The identity's record. Refuses an unknown principal.
	Get(context.Context, *data.GetRequest) (*data.GetResponse, error)
	// Removes the identity. Refuses an unknown principal.
	Delete(context.Context, *data.DeleteRequest) (*data.DeleteResponse, error)
	// The digest of the identity's outstanding grant; unset when none is
	// outstanding. Refuses an unknown principal.
	GetGrantHash(context.Context, *data.GetGrantHashRequest) (*data.GetGrantHashResponse, error)
	// Clears the outstanding grant while its digest still equals the one
	// presented. Refuses when it does not, and clears nothing.
	ClearGrant(context.Context, *data.ClearGrantRequest) (*data.ClearGrantResponse, error)
}

// RegisterServiceHandler registers svc as the identity.data.Service implementation on server.
func RegisterServiceHandler(server *connect.Server, svc ServiceHandler) {
	adapter := serviceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: serviceGetSpec(), Handler: adapter.get},
		connect.Method{Spec: serviceDeleteSpec(), Handler: adapter.delete},
		connect.Method{Spec: serviceGetGrantHashSpec(), Handler: adapter.getGrantHash},
		connect.Method{Spec: serviceClearGrantSpec(), Handler: adapter.clearGrant},
	)
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Get(context.Context, *data.GetRequest) (*data.GetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "identity.data.Service.Get is not implemented")
}

func (UnimplementedServiceHandler) Delete(context.Context, *data.DeleteRequest) (*data.DeleteResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "identity.data.Service.Delete is not implemented")
}

func (UnimplementedServiceHandler) GetGrantHash(context.Context, *data.GetGrantHashRequest) (*data.GetGrantHashResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "identity.data.Service.GetGrantHash is not implemented")
}

func (UnimplementedServiceHandler) ClearGrant(context.Context, *data.ClearGrantRequest) (*data.ClearGrantResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "identity.data.Service.ClearGrant is not implemented")
}

type serviceClient struct {
	client *connect.Client
}

func (c *serviceClient) Get(ctx context.Context, req *data.GetRequest) (*data.GetResponse, error) {
	var res data.GetResponse
	if err := c.client.CallUnary(ctx, serviceGetSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *serviceClient) Delete(ctx context.Context, req *data.DeleteRequest) (*data.DeleteResponse, error) {
	var res data.DeleteResponse
	if err := c.client.CallUnary(ctx, serviceDeleteSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *serviceClient) GetGrantHash(ctx context.Context, req *data.GetGrantHashRequest) (*data.GetGrantHashResponse, error) {
	var res data.GetGrantHashResponse
	if err := c.client.CallUnary(ctx, serviceGetGrantHashSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *serviceClient) ClearGrant(ctx context.Context, req *data.ClearGrantRequest) (*data.ClearGrantResponse, error) {
	var res data.ClearGrantResponse
	if err := c.client.CallUnary(ctx, serviceClearGrantSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type serviceHandler struct{ svc ServiceHandler }

func (h serviceHandler) get(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req data.GetRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Get(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h serviceHandler) delete(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req data.DeleteRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Delete(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h serviceHandler) getGrantHash(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req data.GetGrantHashRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetGrantHash(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h serviceHandler) clearGrant(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req data.ClearGrantRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ClearGrant(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
